spring.application.name=LearningRESTAPIs
spring.h2.console.enabled=true
# Database configuration
# Use this line for in-memory database
# spring.datasource.url=jdbc:h2:mem:learningdb
# Use this line for file-based database
spring.datasource.url=jdbc:h2:file:E:/Java - 6 months/P1-Core_Data (Spring Boot & JPA)/DataBaseOfRestAPIs;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Shivam
spring.datasource.password=Spring@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.path=/h2-console
