spring.application.name=learningSpringBootApp

#This is property name and property value that is used and based of which the data flow and function call of the payment service is triggered!
payment.provider = stripe

#debug = true
#This helps in providing the debugging logs as well when the code is running.